### ISSUE TITLE
Question for the bot

### ISSUE THREAD

**Issue by 3RR0RV2** [suchmememanyskill/discord-mail-forwarder#1]
Hello I have a question please, I do not understand where I have to configure for the bot to work?

**Comment by suchmememanyskill** [comment]
Using environment variables? Either in your docker run command or docker compose yaml file? See the readme for an example

**Comment by 3RR0RV2** [comment]
I want to host it on my computer or on a host, but I don't know where to fill in env.py

**Comment by suchmememanyskill** [comment]
..you use docker

I don't intend for you to use the scripts directly, but even then you can set environment variables and make it work.

Please read up on docker, environment variables and see the readme for which environment variables to set

**Comment by 3RR0RV2** [comment]
![image](https://github.com/suchmememanyskill/discord-mail-forwarder/assets/133774400/46fd949d-557a-4c5a-88b4-b013ea1dffa6)
that not working

![image](https://github.com/suchmememanyskill/discord-mail-forwarder/assets/133774400/ddbc3eae-bcb8-4654-aee0-82d5af48d412)

**Comment by suchmememanyskill** [comment]
Because you're not running it via docker, yes?

Use `docker compose up` in the same folder as the .yaml

**Comment by 3RR0RV2** [comment]
![image](https://github.com/suchmememanyskill/discord-mail-forwarder/assets/133774400/82661bb5-368b-4eed-a048-381631bcf1aa)

**Comment by 3RR0RV2** [comment]
Im looking on google for the error

**Comment by 3RR0RV2** [comment]
It's working thx ;)
